[build]
builder = "NIXPACKS"
buildCommand = "echo 'using nixpacks.toml'"

[deploy]
startCommand = "cd server && sh start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
